# Dockerfile_Proxy
FROM golang:latest

# Set the working directory inside the container
WORKDIR /app

# Copy everything from the current directory to the container
COPY . .

# Print the current directory content for debugging purposes
RUN ls -al

# Set the working directory to /app/src
WORKDIR /app/Lab1/proxy

RUN go mod init myproxy
# Build the Go application
RUN go build -o myproxy


# Expose the port your server listens on
EXPOSE 8080

# Command to run your server
CMD ["./myproxy", "8080"]